server:
  port: 8081
#rabbitmq相关配置
spring:
  rabbitmq:
    #端口号
    port: 5672
    #用户名
    password: guest
    #密码
    username: guest
    #主机
    host: 39.105.231.100
    #虚拟主机(一个RabbitMQ服务可以配置多个虚拟主机，每一个虚拟机主机之间是相互隔离，相互独立的，授权用户到指定的virtual-host就可以发送消息到指定队列)
    virtual-host: /
    #消息发送确认回调
    publisher-confirm-type: correlated
    # 路由失败回调
    publisher-returns: true
    template:
      # 必须设置成true 消息路由失败通知监听者，而不是将消息丢弃
      mandatory: true
    Listener:
      simple:
        # 每次从RabbitMQ获取的消息数量
        prefetch: 3
        default-requeue-rejected: false
        # 每个队列启动的消费者数量
        concurrency: 1
        # 每个队列最大的消费者数量
        max-concurrency: 5
        # 手动签收ACK
        acknowledge-mode: manual

  #数据库连接配置
  datasource:
    username: root
    password: lucong
    url: jdbc:mysql://39.105.231.100:3306/tb_order?characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver

#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xl.demo.entity
  #开启驼峰
  configuration:
    map-underscore-to-camel-case: true
#mapper配置
mapper:
  mappers: com.xl.demo.common.BaseMapper
  identity: MYSQL